### PR TITLE
Support cli config .torus/config.json

### PR DESCRIPTION
**Pull request by nak3**
fixes https://github.com/coreos/torus/issues/176

### CODE REVIEW

**Comment by nak3** [comment]
### Usage example

#### write config file and view
~~~
$ ./bin/torusctl config

$ ./bin/torusctl config --view
{
	"etcd_config": {
		"default": {
			"etcd": "127.0.0.1:2379"
		}
	}
}
~~~

#### write config file with "production" profile and use it

~~~
$ ./bin/torusctl config --profile=production --etcd=https://192.168.133.2:2379 --etcd-ca-file=/path --etcd-cert-file=/path --etcd-key-file=/path

$ ./bin/torusctl config --view
{
	"etcd_config": {
		"default": {
			"etcd": "127.0.0.1:2379"
		},
		"production": {
			"etcd": "https://192.168.133.2:2379",
			"etcd-ca-file": "/path",
			"etcd-cert-file": "/path",
			"etcd-key-file": "/path"
		}
	}
}

$ ./bin/torusctl init --profile=production
~~~

### command line flags win the config file

~~~
$ ./bin/torusctl init --etcd=192.168.133.3
~~~

**Comment by bzub** [comment]
This is great. Can the config file be YAML instead of JSON? Fewer user errors with YAML I think.

**Comment by nak3** [comment]
Thank you. I am prefer `yaml` to `json`.
However, coreos's projects use json for their configuration like [rkt](https://coreos.com/rkt/docs/latest/configuration.html) and [flannel](https://coreos.com/flannel/docs/latest/flannel-config.html). That's the reason why I chose json. And it's up to coreos team.

**Comment by barakmich** [comment]
Yeah, JSON for the config files -- that's why you have a `torusctl config` command. Less user error in doing it that way.

**Pull request merged**
