### PR TITLE
nbd: handle NBD_SET_FLAGS error due to old kernel version

### PR DESCRIPTION
**Pull request by nak3**
fixes https://github.com/coreos/torus/issues/295

### CODE REVIEW

**Comment by nak3** [comment]
Old kernel doesn't support setting `NBD_FLAG_SEND_TRIM` and `NBD_CMD_FLUSH` by `NBD_SET_FLAGS`.
This patch will output following error message instead of stop running process with retuning error. 

~~~
2016-09-17 04:20:48.979478 E | nbd: ioctl returned: inappropriate ioctl for device. kernel version update is strongly recommended.
~~~

**Comment by barakmich** [comment]
A more robust option is to gracefully degrade. Turn off the unsupported flags; we can continue without receiving TRIM for sure, and if CMD_FLUSH never gets sent, we can emulate it by syncing every nominal interval in the degraded case.

**Comment by nak3** [comment]
Alright. I will try. Thank you for your suggestion. (I should have read your comment on  https://github.com/coreos/torus/issues/295)

**Comment by nak3** [comment]
Updated. It might be too straightforward. Any suggestion is welcome.

**Pull request merged**
