### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by fiorix**
These are updates to the documentation files that I went through while
trying Torus for the first time. Was using a remote console so trimmed
the text to 80 cols where possible, removed trailing spaces, and updated
parts of the documentation.

### CODE REVIEW

**Comment by philips** [comment]
Thanks for the contribution!

On our projects we don't word-wrap the docs and generally try to terminate on sentences or paragraphs for two reasons:

1) It makes reading diffs easier in git
2) It keeps us from bike shedding on 72, 78, or 80 character limits

We would love fixes to remove trailing whitespace in a new PR however.

Thanks!

**Comment by fiorix** [comment]
I guess you haven't looked at the changes in the text itself. For example the docker host networking vs what was previously "non-host" networking has been renamed to cluster networking, mentioning networks overlays etc. There's other fixes in the instructions as well, for the record.

**Comment by Ulexus** [comment]
@fiorix he isn't discounting the other fixes, but saying that there are reasons the lines don't wrap.  Just remove the line wrapping and try again.

**Comment by fiorix** [comment]
Yeah, that's fine. Will give it another shot whenever I have time. Cheers.

**Pull request closed without merging**
